### ISSUE TITLE
analysis type is formatted incorrectly

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/metadata-for-user-facility-template-transformations#21]
for analysis_type in the EMSL template the variables should be listed as text.
Need to remove the [] and ' ' around each term.

They should also be separated by a ; not a ,

However, I think there's further discussion to have about if this should be | for both NMDC and EMSL

**Comment by sujaypatil96** [comment]
Fixed in https://github.com/microbiomedata/metadata-for-user-facility-template-transformations/commit/90dd5b5db7a9093fd9f82c4de684da7387727870. List type cells are separated by `;` for no. This issue can be closed.

**Comment by mslarae13** [comment]
@sujaypatil96 
I tested using 7f29bd0b-4616-40d3-aac7-24e450f9f5dc & the metadata didn't export

Can you test this out and let me know if it's working for you?

**Comment by ssarrafan** [comment]
Checked with @mslarae13 and she said she will test but that this should go in the backlog for now.  Natalie may be helping with this in a future sprint. 
FYI @sujaypatil96

**Comment by mslarae13** [comment]
This is still broken. I just tested on 6128ea79-f122-4d14-8588-30f06ce3f1f6

Here's what it looked like : ['metabolomics', 'natural organic matter']
